[package]
name = "nocturne_job"
version = "1.0.0"
authors = []

[addresses]
nocturne_job_addr = "_"

[dev-addresses]
nocturne_job_addr = "0x100"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
