[package]
name = "nocturne_job"
version = "1.0.0"
authors = []

[addresses]
nocturne_job_addr="4488d24ce1fe0d3764007049bd287b02fa511a70f6b193fda3624922c6daf4ba"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
